// Transforms the raw `namelist.json` (~24 MB, dev-only, not published) into
// compact, runtime-ready data modules under `src/data/generated/`.
//
// Why packed strings instead of JSON?
//   - We parse them into Maps ourselves, which is faster and lighter than
//     materializing 103k+ plain objects via JSON.parse.
//   - As `.ts` modules they are bundler-friendly: no `fs`/`fetch` needed, so
//     the library stays isomorphic (works in Node and the browser).
//
// Source of truth for gender is `male_ratio` / `female_ratio`. The dataset's
// `classification` field is intentionally ignored: ~20k rare (frequency 0)
// names are mislabeled "F" there while their ratios are correct.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SOURCE = join(ROOT, "namelist.json");
const OUT_DIR = join(ROOT, "src", "data", "generated");

// When installed as a dependency, namelist.json is absent and the generated
// modules are already present in the published build — nothing to do.
if (!existsSync(SOURCE)) {
  console.log(
    "[build-data] namelist.json not found — skipping (expected when installed as a dependency).",
  );
  process.exit(0);
}

const FIELD_SEP = "|";
const RECORD_SEP = "\n";
const ID_SEP = ",";
const TAG_PREFIX = "tag_";

/** @param {number} r */
const pct = (r) => Math.round(r * 100);

console.log("[build-data] reading", SOURCE);
const raw = JSON.parse(readFileSync(SOURCE, "utf8"));
/** @type {Array<Record<string, any>>} */
const rows = raw.data;
console.log(`[build-data] ${rows.length} names`);

// --- Collect the tag universe so each record can store a compact bitmask ----
const tagIndex = new Map();
for (const row of rows) {
  for (const tag of parseTags(row.tags)) {
    if (!tagIndex.has(tag)) tagIndex.set(tag, tagIndex.size);
  }
}
const TAGS = [...tagIndex.keys()];
if (TAGS.length > 31) {
  // Bitmasks rely on 32-bit safe integers.
  throw new Error(`Too many distinct tags (${TAGS.length}) for a 31-bit mask.`);
}

/** @param {string | undefined} tagsField */
function parseTags(tagsField) {
  if (!tagsField) return [];
  return tagsField
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean)
    .map((t) => (t.startsWith(TAG_PREFIX) ? t.slice(TAG_PREFIX.length) : t));
}

// --- Build the core packed string -------------------------------------------
// One record per line: name|malePct|femalePct|frequency|rank|tagMask
// Line index === numeric id, reused by the trigram index.
const coreLines = new Array(rows.length);
const names = new Array(rows.length);

for (let id = 0; id < rows.length; id++) {
  const row = rows[id];
  const name = row.name;
  names[id] = name;

  let mask = 0;
  for (const tag of parseTags(row.tags)) {
    mask |= 1 << tagIndex.get(tag);
  }

  coreLines[id] = [
    name,
    pct(row.male_ratio),
    pct(row.female_ratio),
    row.frequency_total,
    row["rank (nationwide)"],
    mask,
  ].join(FIELD_SEP);
}

const core = coreLines.join(RECORD_SEP);

// --- Build the trigram index (lazy, fuzzy-only) ------------------------------
// trigram|id,id,...   (ids in base36, ascending). Plain 3-char substrings.
/** @type {Map<string, number[]>} */
const trigramPostings = new Map();

for (let id = 0; id < names.length; id++) {
  const name = names[id];
  const seen = new Set();
  for (let i = 0; i + 3 <= name.length; i++) {
    const tri = name.slice(i, i + 3);
    if (seen.has(tri)) continue;
    seen.add(tri);
    let list = trigramPostings.get(tri);
    if (!list) {
      list = [];
      trigramPostings.set(tri, list);
    }
    list.push(id);
  }
}

const trigramLines = [];
for (const [tri, ids] of [...trigramPostings].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
  trigramLines.push(tri + FIELD_SEP + ids.map((n) => n.toString(36)).join(ID_SEP));
}
const trigrams = trigramLines.join(RECORD_SEP);

// --- Emit modules ------------------------------------------------------------
mkdirSync(OUT_DIR, { recursive: true });

const banner = "// AUTO-GENERATED by scripts/build-data.mjs — do not edit.\n";

writeFileSync(
  join(OUT_DIR, "core.ts"),
  `${banner}export const TAGS: readonly string[] = ${JSON.stringify(TAGS)};\n\nexport const CORE = ${JSON.stringify(core)};\n`,
);

writeFileSync(
  join(OUT_DIR, "trigrams.ts"),
  `${banner}export const TRIGRAMS = ${JSON.stringify(trigrams)};\n`,
);

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(0);
console.log(`[build-data] core.ts      ${kb(core)} KB  (${rows.length} names)`);
console.log(`[build-data] trigrams.ts  ${kb(trigrams)} KB  (${trigramLines.length} trigrams)`);
console.log(`[build-data] tags: ${TAGS.length} -> ${TAGS.join(", ")}`);
console.log("[build-data] done.");
